# Generated by Django 5.0.4 on 2024-05-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='ville',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='produit',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.CharField(blank=True, choices=[('Dresses', 'Dresses'), ('Pants', 'Pants'), ('T-shirts', 'T-shirts'), ('Shoes', 'Shoes'), ('Jackets', 'Jackets')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default='photos/24/04/30/new.jpg', upload_to='photos/%y/%m/%d'),
        ),
    ]
